# Generated by Django 3.2 on 2022-01-24 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='flight number'),
            preserve_default=False,
        ),
    ]
