# Generated by Django 3.2 on 2022-01-26 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20220125_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='uuid'),
        ),
    ]
